from typing import TypedDict

class ProjectState(TypedDict):
    """
    The shared central memory for the multi-agent pipeline.
    """
    user_prompt: str    # Original requirement from the user
    project_plan: str   # Gigh-level architecture roadmap created by Planner
    file_layout: str    # File paths decided by the UI Architect
    generated_code: str # Raw JSX code generated by the Component agent
    final_code: str     # Sanitized, verified code ready for file writing